apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trivy-scanner.fullname" . }}-config
  labels:
    {{- include "trivy-scanner.labels" . | nindent 4 }}
data:
  outputDirs.yaml: |
    imageScanningOutput: "{{ .Values.imageScanning.outputDir }}"
    k8sScanningOutput: "{{ .Values.k8sScanning.outputDir }}"
