kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 5601     # OpenSearch Dashboards
        hostPort: 5601
        protocol: TCP
      - containerPort: 8080     # Zabbix Web UI
        hostPort: 8080
        protocol: TCP

  - role: worker

  - role: worker
