{{- if .Values.logging.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logshipper
  labels:
    {{- include "obsb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: logshipper
  template:
    metadata:
      labels:
        app: logshipper
        {{- include "obsb.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.logging.fluentBit.serviceAccount.name | default "logshipper" }}
      terminationGracePeriodSeconds: 30
      containers:
        - name: fluent-bit
          image: {{ .Values.logging.fluentBit.image | default "cr.fluentbit.io/fluent/fluent-bit:2.2" }}
          args: ["-c", "/fluent-bit/etc/fluent-bit.conf"]
          {{- with .Values.logging.fluentBit.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlogcontainers
              mountPath: /var/log/containers
              readOnly: true
            - name: varlibcontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: logshipper-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlibcontainers
          hostPath:
            path: /var/lib/docker/containers
{{- end }}
