{{- if and .Values.logging.enabled .Values.logging.fluentBit.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.logging.fluentBit.serviceAccount.name | default "logshipper" }}
  labels:
    {{- include "obsb.labels" . | nindent 4 }}
---
{{- end }}

{{- if and .Values.logging.enabled .Values.logging.fluentBit.clusterRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-logshipper" (include "obsb.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "obsb.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-logshipper" (include "obsb.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "obsb.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-logshipper" (include "obsb.fullname" .) | trunc 63 | trimSuffix "-" }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.logging.fluentBit.serviceAccount.name | default "logshipper" }}
    namespace: {{ .Release.Namespace }}
{{- end }}
