{{- if and .Values.zabbix.enabled (gt (len .Values.stacks) 0) }}
{{- range .Values.stacks }}
{{- if and .metrics.enabled (eq .metrics.mode "daemonset") }}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ printf "zabbix-agent-%s" .name | trunc 63 }}
  labels:
    {{- include "obsb.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: zabbix-agent
      stack: {{ .name }}
  template:
    metadata:
      labels:
        app: zabbix-agent
        stack: {{ .name }}
    spec:
      containers:
        - name: zabbix-agent
          image: zabbix/zabbix-agent:latest
          env:
            - name: ZBX_SERVER_HOST
              value: "{{ $.Values.zabbix.serverHost | default "zabbix" }}"
            - name: ZBX_SERVER_ACTIVE
              value: "{{ $.Values.zabbix.serverHost | default "zabbix" }}"
            - name: ZBX_STARTAGENTS
              value: "5"
            - name: ZBX_HOSTNAME
              {{- if $.Values.zabbix.agent.hostnameFromNode }}
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
              {{- else }}
              value: "{{ .name }}"
              {{- end }}
            - name: ZBX_METADATA
              value: "{{ default $.Values.zabbix.agent.metadata .metrics.metadata }}"
          volumeMounts:
            - name: host-root
              mountPath: /rootfs
              readOnly: true
      volumes:
        - name: host-root
          hostPath:
            path: /
{{- end }}
{{- end }}
{{- end }}
