{{- if and .Values.zabbix.enabled .Values.zabbix.kubernetes.enabled }}
{{- if .Values.zabbix.kubernetes.createServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.zabbix.kubernetes.serviceAccountName | default "zabbix-k8s" }}
  labels:
    {{- include "obsb.labels" . | nindent 4 }}
---
{{- end }}
{{- if .Values.zabbix.kubernetes.clusterRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-zabbix-k8s" (include "obsb.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "obsb.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.zabbix.kubernetes.clusterRole.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-zabbix-k8s" (include "obsb.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "obsb.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-zabbix-k8s" (include "obsb.fullname" .) | trunc 63 | trimSuffix "-" }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.zabbix.kubernetes.serviceAccountName | default "zabbix-k8s" }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
